defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV["PG_HOST"] %>
  port:     <%= ENV["PG_PORT"] || 5432 %>
  database: <%= ENV["PG_DATABASE_NAME"] %>
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>

development:
  <<: *defaults
  pool: 5

test:
  <<: *defaults
  pool: 5
  database: <%= ENV["PG_TEST_DATABASE_NAME"] || "test" %><%= ENV["TEST_ENV_NUMBER"] %>
  username: <%= ENV["PG_TEST_USERNAME"] || ENV["PG_USER"] %>
  password: <%= ENV["PG_TEST_PASSWORD"] || ENV["PG_PASSWORD"] %>

staging:
  <<: *defaults
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>

production:
  <<: *defaults